# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-05-01 15:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('status_email', models.CharField(choices=[(b'A', b'Ativo'), (b'N', b'N\xc3\xa3o confirmado'), (b'I', b'Inv\xc3\xa1lido'), (b'S', b'Spam'), (b'O', b'Opt-out')], default=b'N', max_length=1, verbose_name=b'Status Email')),
            ],
        ),
    ]
