# Generated by Django 2.1 on 2020-08-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='status_email',
            field=models.CharField(choices=[('A', 'Ativo'), ('N', 'Não confirmado'), ('I', 'Inválido'), ('S', 'Spam'), ('O', 'Opt-out')], default='N', max_length=1, verbose_name='Status Email'),
        ),
    ]
