# Generated by Django 2.1 on 2020-08-13 14:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filebrowser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='filebrowser_logentry_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
