# Generated by Django 3.2.18 on 2023-04-13 15:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filebrowser', '0002_auto_20200813_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filebrowser_logentry_set', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
    ]
