# Generated by Django 2.2.24 on 2021-08-11 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='group',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Grupo'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='media',
            field=models.URLField(blank=True, null=True, verbose_name='Media'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.TextField(blank=True, null=True, verbose_name='Título'),
        ),
    ]
