# Generated by Django 2.2.24 on 2021-10-20 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_csv'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Csv',
        ),
        migrations.AddField(
            model_name='noticia',
            name='fonte',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Fonte de Dados'),
        ),
    ]
