# Generated by Django 2.2.24 on 2021-10-13 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_csv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='dt',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='media',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='titulo',
        ),
        migrations.RemoveField(
            model_name='noticia',
            name='url',
        ),
    ]
