# Generated by Django 2.2.24 on 2021-10-13 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211013_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='background',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='day',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='headline',
            field=models.TextField(blank=True, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='media',
            field=models.URLField(blank=True, null=True, verbose_name='Media'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='media_caption',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='media_credit',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='noticia',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
