# Generated by Django 2.2.24 on 2021-11-02 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20211020_2132'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='group',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
