# Generated by Django 2.2.24 on 2022-01-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20211102_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Busca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now_add=True)),
                ('hash', models.CharField(db_index=True, max_length=20)),
                ('count', models.IntegerField()),
                ('busca', models.TextField()),
            ],
        ),
    ]
