# Generated by Django 2.2.24 on 2022-01-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_busca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='media',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Media'),
        ),
    ]
