# Generated by Django 2.2.24 on 2022-01-31 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20220129_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='url_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
