# Generated by Django 2.2.24 on 2022-02-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_auto_20220131_1154'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticia',
            options={'ordering': ('dt',), 'verbose_name': 'Notícia'},
        ),
        migrations.AddField(
            model_name='noticia',
            name='texto_completo',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Completo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='dt',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='texto',
            field=models.TextField(blank=True, null=True, verbose_name='Texto Base'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='titulo',
            field=models.TextField(verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url_hash',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
