# Generated by Django 2.2.24 on 2022-03-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20220201_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='url_valida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='atualizado',
            field=models.BooleanField(default=False),
        ),
    ]
