# Generated by Django 2.2.24 on 2022-03-08 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20220304_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='termo',
            name='texto_explicativo',
            field=models.TextField(null=True),
        ),
    ]
