# Generated by Django 2.2.24 on 2022-03-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_noticia_texto_busca'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='revisado',
            field=models.BooleanField(default=False),
        ),
    ]
