# Generated by Django 2.2.24 on 2022-03-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_noticia_revisado'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='imagem',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='fonte',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Fonte da Notícia'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='media',
            field=models.URLField(blank=True, max_length=400, null=True, verbose_name='Imagem'),
        ),
    ]
