# Generated by Django 2.2.24 on 2022-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_noticia_id_externo'),
    ]

    operations = [
        migrations.AddField(
            model_name='assunto',
            name='id_externo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='assunto',
            index=models.Index(fields=['termo', 'id_externo'], name='termo_idx'),
        ),
    ]
