# Generated by Django 2.2.24 on 2022-07-31 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_termo_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
    ]
