# Generated by Django 2.2.24 on 2022-08-05 09:23

from django.db import migrations, models


def clean_images(apps, schema_editor):
    Noticia = apps.get_model("base", "Noticia")
    for r in Noticia.objects.filter(imagem__isnull=False):
        if not r.imagem.startswith('/media'):
            if r.imagem.startswith('media'):
                r.imagem = '/' + r.imagem
            else:
                r.imagem = None
            r.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_noticia_notas'),
    ]

    operations = [
        migrations.RunPython(clean_images),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Imagem Local'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='media',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Imagem'),
        ),
    ]
