# Generated by Django 2.2.24 on 2022-08-15 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20220805_0923'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='coletanea',
            field=models.BooleanField(default=False, verbose_name='Coletânea'),
        ),
    ]
