# Generated by Django 3.2.18 on 2023-07-05 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20230413_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Canal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('domain', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='assunto',
            name='termo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.termo', verbose_name='Timeline'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='atualizado',
            field=models.BooleanField(default=False, help_text='Indica que o texto da notícia foi capturado', verbose_name='Texto atualizado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='coletanea',
            field=models.BooleanField(default=False, help_text='Indica que o artigo é uma coletânea de várias notícias', verbose_name='Coletânea'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='notas',
            field=models.TextField(blank=True, help_text='Notas sobre a coleta', null=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='pdf_atualizado',
            field=models.BooleanField(default=False, help_text='Indica que o PDF da página já está arquivado', verbose_name='PDF gerado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='revisado',
            field=models.BooleanField(default=False, help_text='Permite que editor indique que o texto foi revisado. Após esta marcação, o sistema não atualiza mais nenhuma informação.', verbose_name='Texto revisado'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='url_valida',
            field=models.BooleanField(default=False, help_text='Indica que a URL foi validada. Para revalidá-la, clique no botão Capturar Texto', verbose_name='URL Válida'),
        ),
        migrations.CreateModel(
            name='CanalRegra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_regra', models.CharField(choices=[('C', 'Contém'), ('I', 'Ignore')], max_length=1)),
                ('regra', models.TextField()),
                ('canal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.canal')),
            ],
            options={
                'verbose_name': 'Regra do Canal',
            },
        ),
    ]
