# Generated by Django 3.2.18 on 2023-04-13 15:35

from django.db import migrations
import imagestore.utils
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0003_auto_20200813_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=sorl.thumbnail.fields.ImageField(max_length=255, upload_to=imagestore.utils.FilePathGenerator(to='uploads/gallery/'), verbose_name='File'),
        ),
    ]
