# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-01-28 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('token', models.CharField(default=utils.models.create_token, max_length=30, primary_key=True, serialize=False)),
                ('owner', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
